declare const FormulaLexer_base: any;
declare class FormulaLexer extends FormulaLexer_base {
    [x: string]: any;
    static grammarFileName: string;
    static channelNames: string[];
    static modeNames: string[];
    static literalNames: string[];
    static symbolicNames: string[];
    static ruleNames: string[];
    constructor(input: any);
    _interp: any;
}
declare namespace FormulaLexer {
    let EOF: any;
    let T__0: number;
    let T__1: number;
    let T__2: number;
    let T__3: number;
    let T__4: number;
    let T__5: number;
    let T__6: number;
    let T__7: number;
    let COMMENT: number;
    let LINE_COMMENT: number;
    let R__: number;
    let R_: number;
    let NEWLINES: number;
    let WHILESTATEMENT: number;
    let FORSTATEMENT: number;
    let FROMSTATEMENT: number;
    let INSTATEMENT: number;
    let TOSTATEMENT: number;
    let BYSTATEMENT: number;
    let LOOPSTATEMENT: number;
    let IFSTATEMENT: number;
    let THENSTATEMENT: number;
    let ELSESTATEMENT: number;
    let FUNCTIONSTATEMENT: number;
    let ENDBLOCK: number;
    let RETURNSTATEMENT: number;
    let NEWSTATEMENT: number;
    let TRYSTATEMENT: number;
    let CATCHSTATEMENT: number;
    let THROWSTATEMENT: number;
    let OR: number;
    let XOR: number;
    let AND: number;
    let EQUALS: number;
    let NOTEQUALS: number;
    let LT: number;
    let LTEQ: number;
    let GT: number;
    let GTEQ: number;
    let PLUS: number;
    let MINUS: number;
    let MULT: number;
    let DIV: number;
    let MOD: number;
    let POW: number;
    let LARR: number;
    let RARR: number;
    let LCURL: number;
    let RCURL: number;
    let INTEGER: number;
    let FLOAT: number;
    let BOOL: number;
    let PER: number;
    let SQUARED: number;
    let CUBED: number;
    let IDENT: number;
    let PRIMITIVE: number;
    let LBRACKET: number;
    let RBRACKET: number;
    let SPACE: number;
    let STRING: number;
}
export default FormulaLexer;
